Pdf convert
profcomff/print-api pull request #11
Opened 2022-11-21 13:51 UTC by nmkazantsev

добавил конвертацию поступающих файлов (картинок) в pdf с изменением иемни файла (меняю только расширение) в бд
Если картинка не в горизонтальной ориентации, то она поворачивается, чтобы картинка была на весь лист

2022-11-21 14:06 UTC, grigoriev-semyon commented on .gitignore
> +.vscode/launch.json
это должно быть в глобальном гитигноре

2022-11-21 14:11 UTC, grigoriev-semyon commented on .gitignore
> +.vscode/launch.json
https://stackoverflow.com/questions/7335420/global-git-ignore

2022-11-22 13:10 UTC, grigoriev-semyon requested changes

2022-11-22 13:10 UTC, grigoriev-semyon commented on print_service/utils.py
> +def process_image(filepath,newFileName):
добавить тайп хинты
сделать async

2022-11-22 13:10 UTC, grigoriev-semyon commented on print_service/utils.py
> +        width, height = image.size
зачем эти переменные создавать?

2022-11-22 13:10 UTC, grigoriev-semyon commented on print_service/api_routes/file.py
> +        remove(path)# удаляем старый файл - картинку
try except

2022-11-22 13:13 UTC, grigoriev-semyon commented
также не хватает тестов на новый функционал 
их тут добавить можно очень быстро

2022-11-22 13:17 UTC, dyakovri commented on print_service/api_routes/file.py
> +        process_image(path,path.replace(fileFormat,"pdf"))
Блокируешь поток
Лучше сохранять себе картинку и начинать ее обрабатывать в pdf через [BackgroundTask](https://fastapi.tiangolo.com/tutorial/background-tasks/)

2022-11-22 13:23 UTC, dyakovri commented on print_service/utils.py
> +def process_image(filepath,newFileName):
Зачем асинк?

2022-11-22 13:37 UTC, grigoriev-semyon commented on print_service/utils.py
> +def process_image(filepath,newFileName):
отмена
async не делать

2022-11-22 13:37 UTC, grigoriev-semyon commented on print_service/utils.py
> +def process_image(filepath,newFileName):
подумай
если отдать код до конвертации может ли выдать ошибку оно в процессе конвертации?

2022-11-23 14:54 UTC, mixx3 commented on print_service/api_routes/file.py
> +    if(file.content_type=="image/png"):
или os.path.splitext(path)

2022-11-23 18:36 UTC, grigoriev-semyon commented on print_service/settings.py
> +    CONTENT_TYPES: List[str] = ['application/pdf','image/png','image/jpeg']
ну в некоторых случаях получше уже будет

2022-11-26 16:58 UTC, nmkazantsev commented on print_service/api_routes/file.py
> +        process_image(path,path.replace(fileFormat,"pdf"))
Ничего ведь страшного в том, что после переделки всего кода (у меня теперь обработка файла в background task)  у меня имя файла будет как переменная+"pdf"? Не f строка, но читабельно

2022-11-26 17:23 UTC, grigoriev-semyon commented on print_service/api_routes/file.py
> +        process_image(path,path.replace(fileFormat,"pdf"))
Лучше не надо. f строки быстрее и читабельнее

2022-11-26 19:55 UTC, grigoriev-semyon commented on print_service/api_routes/file.py
> +        background_tasks.add_task (process_image,memory_file,fileName) #сама конвертация в фоне, .pdf поставит функция
тут какой то пробел

2022-11-26 20:02 UTC, nmkazantsev commented on print_service/api_routes/file.py
> +        background_tasks.add_task (process_image,memory_file,fileName) #сама конвертация в фоне, .pdf поставит функция
а что тут не так? Зачем нам писать файл и закрвать его, если я его не открыл, а сохраню я его позже уже в пдф?

2022-11-26 20:05 UTC, grigoriev-semyon commented on print_service/utils.py
> +def process_image(filepath,newFileName):
тайп хинтов не вижу

2023-03-16 13:40 UTC, closed without merging