Print-pages limit.
profcomff/print-api pull request #50
Opened 2023-05-15 17:09 UTC by Temmmmmo

## Изменения
В настройках можно указать ограничение на количество листов, которые можно распечатать на принтере.

## Реализации
1. Добавлена функция, считающая количество листов, которые израсходуются на печать данного файла.
2. Создан новый столбец с данными о количестве напечатанных листов в таблице, использующейся для статистики. 

## Детали
1. Реализованная функция подсчета, позволяет из строки вида '1, 2, 4-10, 1-8' получить количество листов, которые будут напечатаны.
2. Новый столбец sheet_used добавлен в таблицу PrintFact.

## Check-List
- [x] Вы проверили свой код перед отправкой запроса?
- [x] Вы написали тесты к реализованным функциям? 
- [x] Вы не забыли применить black и isort?

***P.S. Проставьте x в квадратные скобки в нужных пунктах. Example: [x]***

2023-05-15 17:27 UTC, dyakovri commented on migrations/versions/d63e9f7661dd_page_count.py
> +    op.add_column('print_fact', sa.Column('sheet_used', sa.Integer(), nullable=False))
Может рассчитать для текущих принтфактов запросом? А потом сделать Nullable False?

2023-05-15 17:31 UTC, dyakovri commented on print_service/utils/__init__.py
> +        return len(result) * copy_count
Мне кажется, что в модель `class File(Model):` это добавить логичнее
Отдельная функция для `flatten_pages` (превращает `1-2,4` в `{1,2,4}`) и отдельная для `sheet_count` (количество затраченных листов)
Кажется, тут отлично подойдут `property`

2023-05-15 17:32 UTC, grigoriev-semyon requested changes

2023-05-15 17:32 UTC, grigoriev-semyon commented on migrations/versions/d63e9f7661dd_page_count.py
> +    # ### commands auto generated by Alembic - please adjust! ###
Комменты убери)

2023-05-15 17:32 UTC, grigoriev-semyon commented on print_service/models/__init__.py
> +    sheet_used: Mapped[int] = Column(Integer, nullable=False)
sheets_used

2023-05-15 17:32 UTC, grigoriev-semyon commented on print_service/utils/__init__.py
> +    if page == '':
Непонятно сходу что такое page

2023-05-15 17:32 UTC, grigoriev-semyon commented on print_service/utils/__init__.py
> +        return math.ceil(len(result) / 2) * copy_count
Но result получается массив рейнджей
Его длина это количество уникальных ренджей но не сумма всех отрезков

2023-05-15 17:33 UTC, dyakovri commented on print_service/utils/__init__.py
> +        _, number_of_pages = checking_for_pdf(f)
Я бы тут еще проверял, что `number of pages >= max(pages)`, то есть количество страниц в файле больше, чем максимально запрашиваемая страничка через настройку "номера страниц"

2023-05-15 17:33 UTC, grigoriev-semyon commented on print_service/utils/__init__.py
> +        result.update(range(int(x[0]), int(x[-1]) + 1))
Почему не что то типа 
+=(x[-1]+1-x[0])? 
Это количество страниц без сетов

2023-05-15 17:36 UTC, Temmmmmo commented on print_service/utils/__init__.py
> +        result.update(range(int(x[0]), int(x[-1]) + 1))
Там идея реализации, чтобы всё не падало, если придет строка '1-5, 3'. В таком случае страниц будет 5, а если сделать так, как ты говоришь, то 3 лишний раз посчитается и будет 6.

2023-05-15 17:36 UTC, grigoriev-semyon commented
По моему ты там нагородил функцию из асбстракций который можно сломать когда количество уникальных записей в «1,2,3,…» больше чем количество страниц

2023-05-15 17:38 UTC, dyakovri commented on print_service/models/__init__.py
> +    sheet_used: Mapped[int] = Column(Integer, nullable=False)
Говешки использованные))

2023-05-15 17:39 UTC, dyakovri commented on print_service/utils/__init__.py
> +        return math.ceil(len(result) / 2) * copy_count
![image](https://github.com/profcomff/print-api/assets/5656720/21c618dd-c352-44f4-92ff-52a40e18068c)

2023-05-15 17:40 UTC, dyakovri commented on print_service/utils/__init__.py
> +        result.update(range(int(x[0]), int(x[-1]) + 1))
Интересно, а как реально будет распечатано в случае '1-5, 3'

2023-05-15 17:43 UTC, grigoriev-semyon commented on print_service/utils/__init__.py
> +        return len(result) * copy_count
А почему не так как я сказал? 
Можно вынести в отдельную функцию но я думаю можно без сетов и ренджей

2023-05-15 17:47 UTC, mrerro commented on print_service/utils/__init__.py
> +        result.update(range(int(x[0]), int(x[-1]) + 1))
можно даже что то в духе `1,1,1,1,1` и получить 5 первых страниц напечатанных. Это я говорю со стороны печати, такие записи валидны.

2023-05-15 21:50 UTC, dyakovri commented on print_service/models/__init__.py
> +                return (self.number_of_pages // 2 + 1) * self.option_copies
2 страницы => 2/2+1=2, что неверно 
Обычное деление, но округление вверх через math.ceil

2023-05-15 21:50 UTC, dyakovri commented on print_service/models/__init__.py
> +                return self.number_of_pages * self.option_copies
Two sided можно один раз обработать как `bool(two sided) / 2`

2023-05-15 21:50 UTC, dyakovri commented on print_service/routes/admin.py
> +    raise TerminalNotFound('token')
Что за строка 'token'?

2023-05-15 21:50 UTC, dyakovri commented on print_service/routes/file.py
> +        raise NotInUnion
Кажется, рейзить надо объекты, а не классы. Да, классы без аргументов норм рейзятся и так, но лучше все таки скобки не забывать

2023-05-15 21:50 UTC, dyakovri commented on print_service/settings.py
> +    MAX_PAGE_COUNT: int = 5
Давай умолчание не 5, а 20 хотя бы
И в .github/workflows настройки добавь плз

2023-05-21 14:11 UTC, grigoriev-semyon requested changes

2023-05-21 14:11 UTC, grigoriev-semyon commented on print_service/models/__init__.py
> +    def flatten_pages(self) -> list | None:
лист чего? list[?]

2023-05-21 14:11 UTC, grigoriev-semyon commented on print_service/models/__init__.py
> +    def flatten_pages(self) -> list | None:
напиши пж докстрингу что эта штука делает

2023-05-21 14:11 UTC, grigoriev-semyon commented on print_service/models/__init__.py
> +    def sheets_count(self) -> int | None:
напиши пж докстрингу что эта штука делает

2023-05-21 14:11 UTC, grigoriev-semyon commented on print_service/routes/exc_handlers.py
> +    )
одинаковые названия

2023-05-21 14:11 UTC, grigoriev-semyon commented on print_service/routes/exc_handlers.py
> +    )
одинаковые названия

2023-05-21 14:11 UTC, grigoriev-semyon commented on print_service/routes/exc_handlers.py
> +async def already_upload(req: starlette.requests.Request, exc: AlreadyUpload):
uploaded

2023-05-21 14:11 UTC, grigoriev-semyon commented on print_service/routes/exc_handlers.py
> +async def is_corrupt(req: starlette.requests.Request, exc: IsCorrupt):
corrupted

2023-05-21 14:11 UTC, grigoriev-semyon commented on print_service/routes/file.py
> +        raise ex
нахрена?

2023-05-21 14:11 UTC, grigoriev-semyon commented on print_service/routes/file.py
> +        raise AlreadyUpload()
await file.close()
raise

2023-05-21 14:11 UTC, grigoriev-semyon commented on print_service/routes/file.py
> +            raise TooLargeSize()
await file.close()
raise

2023-05-21 14:11 UTC, grigoriev-semyon commented on print_service/routes/file.py
> +        raise IsCorrupt()
await file.close()
raise

2023-05-21 14:11 UTC, grigoriev-semyon commented on print_service/routes/file.py
> +            raise InvalidPageRequest()
await file.close()
raise

2023-05-21 14:11 UTC, grigoriev-semyon commented on print_service/routes/file.py
> +        raise TooManyPages()
await file.close()
raise

2023-05-21 14:11 UTC, grigoriev-semyon commented on print_service/routes/qrprint.py
> +            raise ex
нахрена?

2023-05-21 15:57 UTC, Temmmmmo commented on print_service/routes/file.py
> +        raise ex
Чтобы хэндлер ловил это, ошибки в функциях в утилсах не видны хэндлерами

2023-05-21 22:59 UTC, grigoriev-semyon requested changes
Не исправлено ничего из моего ревью

2023-05-22 16:19 UTC, Temmmmmo commented on print_service/models/__init__.py
> +    def flatten_pages(self) -> list | None:
list[int]
Исправил

2023-05-22 16:19 UTC, Temmmmmo commented on print_service/models/__init__.py
> +    def sheets_count(self) -> int | None:
Написал

2023-05-22 16:19 UTC, Temmmmmo commented on print_service/routes/exc_handlers.py
> +    )
Исправил

2023-05-22 16:19 UTC, Temmmmmo commented on print_service/routes/file.py
> +        raise ex
Убрал. Без них работает

2023-05-22 16:20 UTC, Temmmmmo commented on print_service/routes/file.py
> +        raise AlreadyUpload()
Добавил

2023-05-22 16:20 UTC, Temmmmmo commented on print_service/routes/file.py
> +        raise IsCorrupt()
Добавил

2023-05-22 16:20 UTC, Temmmmmo commented on print_service/routes/file.py
> +        raise TooManyPages()
Добавил

2023-05-22 16:20 UTC, Temmmmmo commented on print_service/routes/file.py
> +            raise InvalidPageRequest()
Добавил

2023-05-22 16:20 UTC, Temmmmmo commented on print_service/routes/qrprint.py
> +            raise ex
Убрал. Без этого работает.

2023-05-22 16:28 UTC, grigoriev-semyon commented on print_service/models/__init__.py
> +        "1-5, 3, 2"'''
список чисел - непонятно

2023-05-22 16:29 UTC, grigoriev-semyon commented on print_service/models/__init__.py
> +        "1-5, 3, 2"'''
тоже непонятно

2023-05-22 16:31 UTC, grigoriev-semyon commented on print_service/routes/exc_handlers.py
> +    )
не вижу

2023-05-22 17:36 UTC, grigoriev-semyon approved these changes

2023-05-22 17:38 UTC, merged