Print api 29 soft deletes
profcomff/print-api pull request #69
Opened 2023-11-13 19:38 UTC by lisikust

## Изменения
Добавлен столбец `is_deleted` в директории `models`, файл `__init__`
Изменен router `update_list` и класс `UserCreate` в директории `routes`, файл `users`

2023-11-14 10:19 UTC, mixx3 requested changes

2023-11-14 10:19 UTC, mixx3 commented on print_service/models/__init__.py
> +    is_deleted: Mapped[bool] = mapped_column(Boolean)
add migration pls
`
alembic revision autogenerate -m "message"
`
https://alembic.sqlalchemy.org/en/latest/tutorial.html

2023-11-14 10:19 UTC, mixx3 commented on print_service/routes/user.py
> +    is_deleted: bool
i think it should be false by default

2023-11-14 12:16 UTC, Wudext commented on print_service/models/__init__.py
> +    is_deleted: Mapped[bool] = mapped_column(Boolean)
alembic revision --autogenerate -m "message"

Тогда уж

2023-11-14 12:18 UTC, Wudext requested changes
Удали все .DS_Store файлы и проведи миграцию:

alembic revision --autogenerate -m "soft_deletes"

2023-11-14 12:18 UTC, Wudext commented on .DS_Store
.DS_Store файлы коммитить не надо, снеси их

2023-11-14 12:18 UTC, Wudext commented on print_service/.DS_Store
И этот тоже снеси

2023-11-14 12:21 UTC, Wudext commented on print_service/routes/user.py
> +    is_deleted: bool
Тут как будто бы еще \ в конце 27 строчки лишний

2023-11-16 20:24 UTC, lisikust commented
Migration has been added. 
`is_deleted` column is made `False` by default.

2023-12-04 11:39 UTC, closed without merging