Добавил проверку на наличие скоупа print.file.send
profcomff/print-api pull request #88
Opened 2024-10-26 20:26 UTC by BombinBM

В коде добавил опциональность для ввода номера билета, а так же проверку на наличие скоупа внутри имеющихся у юзера. в выводе оставил только имя юзера.

2024-11-03 20:47 UTC, Temmmmmo commented
линтинг упал, пропиши 
`black .`
`isort .`

2024-11-03 20:57 UTC, Temmmmmo commented
тебе нужен был файл `file.py`
там нужно было разобраться с одной ручкой, отвечающей за отправку файлов
метод check_union_member тебе вероятно не нужен)

2024-11-22 08:27 UTC, parfenovma requested changes, later dismissed
лучше ветки на англ называть
![Uploading image.png…]()

2024-11-22 08:27 UTC, parfenovma commented on print_service/routes/file.py
> +    inp: SendInput,
нет тайп хинта, непонятное название

2024-11-22 08:27 UTC, parfenovma commented on print_service/routes/file.py
> +    has_send_scope: bool = Depends(has_send_scope),
обычно булевые переменнные начинаются с is_ или заканчиваются _flg

2024-11-22 08:27 UTC, parfenovma commented on print_service/routes/file.py
> +            detail="Поле number обязательно для пользователей без скоупа print.file.send",
не юзер френдли ошибка. Она же на фронт пойдет, зачем нам писать служебную информацию? 
И наверное это 403 всё-таки

2024-11-22 08:27 UTC, parfenovma commented on print_service/routes/file.py
> +    if inp.number is not None:
`if inp.number:`

2024-11-24 21:23 UTC, Temmmmmo commented on print_service/routes/file.py
> +    else:
давай этот else уберем и реализуем иначе

2024-11-24 21:23 UTC, Temmmmmo commented on print_service/routes/file.py
>      if not user:
вот тут добавим также проверку на наличие скоупа

2024-11-24 21:23 UTC, Temmmmmo commented on print_service/routes/file.py
>      if not user:
то есть если у чела не прописаны ни номер билета, ни фио, ни студак, но при этом есть скоуп, то все хорошо, ошибку не рейзим

2024-11-24 21:23 UTC, Temmmmmo commented on print_service/routes/file.py
> +def has_send_scope(
давай не будем это выносить в отдельную функцию

2024-11-24 21:23 UTC, Temmmmmo commented on print_service/routes/file.py
> +    settings: Settings = Depends(get_settings),
депендс пропишем прям тут, это норм

2024-11-24 21:23 UTC, Temmmmmo commented on print_service/routes/file.py
>          description='Фамилия',
смотри, surname тоже становится необязательным для пользователей со скоупом, давай учтем это

2024-11-24 21:23 UTC, Temmmmmo commented on print_service/routes/file.py
> +    settings: Settings = Depends(get_settings),
депендс от юнионаутха я имею в виду

2024-11-24 21:23 UTC, Temmmmmo commented on print_service/routes/file.py
> +    settings: Settings = Depends(get_settings),
назовем его user, тогда в дальнейшем оттуда мы сможем еще получать user_id

2024-11-24 21:23 UTC, Temmmmmo commented on print_service/routes/user.py
> +    number: Optional[str] = constr(strip_whitespace=True, to_upper=True, min_length=1),
не уверен, что тут надо делать поле опциональным
т.к. для пользователей со скоупом в принципе не планируется прокидывание проверки на присутствие в профсоюзе

2024-12-11 11:26 UTC, BombinBM commented on print_service/routes/file.py
> +    settings: Settings = Depends(get_settings),
auth_user

2024-12-11 11:31 UTC, BombinBM commented on print_service/routes/file.py
>      if not user:
if user is None

2024-12-11 11:32 UTC, BombinBM commented on print_service/routes/file.py
> +    if inp.number is not None:
and inp.surname is not None

2024-12-11 11:36 UTC, BombinBM commented on print_service/routes/file.py
> +        if not "print.file.send" in [scope["name"] for scope in user.get('session_scopes')]:
elif

2025-02-06 12:00 UTC, Temmmmmo reviewed
Да вроде нормально
Ты тестил?

2025-02-06 12:00 UTC, Temmmmmo reviewed
Да вроде нормально
Ты тестил?

2025-02-06 12:03 UTC, Temmmmmo commented on print_service/routes/file.py
> +            raise NotInUnion()
Единственное, возможно стоит ошибку тут другую кидать, иначе с ходу непонятно: это у тебя скоупа нет или тебя в профсоюзе нет

2025-02-06 15:05 UTC, BombinBM commented on print_service/routes/file.py
> +            raise NotInUnion()
Тестил локально, да.

Насчет ошибки не уверен. У нас же скоуп должен быть всегда, если человек состоит в профсоюзе

2025-02-15 18:02 UTC, Temmmmmo reviewed
как будто норм, пофикси последний комм и мерджим

2025-02-15 18:02 UTC, Temmmmmo commented on print_service/__main__.py
> +    uvicorn.run("print_service.routes.base:app", reload=True)
убрать

2025-02-15 18:11 UTC, BombinBM commented on print_service/__main__.py
> +    uvicorn.run("print_service.routes.base:app", reload=True)
Сделал

2025-02-15 18:22 UTC, Temmmmmo requested changes

2025-02-15 18:22 UTC, Temmmmmo commented on print_service/__main__.py
>      uvicorn.run(app)
Будет ошибка
app not found

2025-02-15 18:35 UTC, BombinBM commented on print_service/__main__.py
>      uvicorn.run(app)
Да, добавил импорт. Теперь запускается и ручки работают

2025-02-16 08:58 UTC, Temmmmmo approved these changes

2025-03-07 21:05 UTC, merged